spring:
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/dev

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    org.springframework.security: INFO
